//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumContent
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int User_Id { get; set; }
        public int Forum_Id { get; set; }
    
        public virtual ForumTitles ForumTitles { get; set; }
    }
}
